import Head from 'next/head'
import MainWrapper from '../components/MainWrapper'
import Nav from '../components/Navbar'
import SecondPageWrapper from '../components/SecondPageWrapper'
import styles from '../styles/Home.module.css'

export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />

        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;700;800&display=swap'
          rel='stylesheet'
        />
      </Head>
      <main className='background-dark'>
        <Nav />
        <MainWrapper />
        <SecondPageWrapper />
      </main>
    </div>
  )
}
