import Head from 'next/head'
import MainWrapper from '../components/MainWrapper'
import Nav from '../components/Navbar'
import SecondPageWrapper from '../components/SecondPageWrapper'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='background-dark'>
        <Nav />
        <MainWrapper />
        <SecondPageWrapper />

        <ToastContainer />
      </main>
    </div>
  )
}
